str = input("Wprowadź tekst mający co najmniej siedem znaków: ")
print("Ten tekst zawiera ", len(str), " znaków")
print("Pierwszy znak tego tesktu to: ", str[0])
print("Ostatni znak tego tesktu to: ", str[-1])
print("Trzy losowe znaki ze środka tesktu", str[3:6])
